version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "madhun2319"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
